---
application_id: svc-cache-registry
entity_name: "{{ application_id | get_entity_name }}"

REGISTRY_CACHE_IMAGE: "{{ lookup('config', application_id, 'services.cache-registry.image') }}"
REGISTRY_CACHE_VERSION: "{{ lookup('config', application_id, 'services.cache-registry.version') }}"
REGISTRY_CACHE_CONTAINER: "{{ lookup('config', application_id, 'services.cache-registry.name') }}"
REGISTRY_CACHE_PORT: "{{ lookup('config', application_id, 'services.cache-registry.ports.local.registry') }}"
REGISTRY_CACHE_PROXY_REMOTE_URL: "{{ lookup('config', application_id, 'services.cache-registry.proxy.remote_url') }}"
REGISTRY_CACHE_DATA_VOLUME: "{{ lookup('config', application_id, 'volumes.data.name') }}"
