---
synapse_data:
  type: volume
  name: matrix_synapse_data
  mounts:
    - service: synapse
      target: /data

chatgpt_data:
  type: volume
  name: matrix_chatgpt_data
  mounts:
    - service: matrix-chatgpt-bot
      target: /storage

synapse_config:
  type: bind
  source: "{{ [ lookup('container', 'web-app-matrix', 'directories.config'), 'homeserver.yaml' ] | path_join }}"
  read_only: true
  mounts:
    - service: synapse
      target: /data/homeserver.yaml

synapse_log:
  type: bind
  source: "{{ [ lookup('container', 'web-app-matrix', 'directories.config'), (lookup('domains', 'web-app-matrix').synapse) ~ '.log.config' ] | path_join }}"
  read_only: true
  mounts:
    - service: synapse
      target: "/data/{{ lookup('domains', 'web-app-matrix').synapse }}.log.config"

element_config:
  type: bind
  source: "{{ [ lookup('container', 'web-app-matrix', 'directories.config'), 'element-config.json' ] | path_join }}"
  mounts:
    - service: element
      target: /app/config.json
