---
whitelist:
  media-src:
    - "blob:"
  script-src:
    - "blob:"
  style-src-elem:
    - https://fonts.googleapis.com # nocheck: external-cdn,url
  font-src:
    - https://fonts.gstatic.com # nocheck: external-cdn,url
